#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Admin
admin:
  path:       /admin/{page_name}/{parameter}
  controller: App\Controller\AdminController::index
  defaults:
    page_name:  null
    parameter: null